### ISSUE TITLE
Error: "true" is not a boolean

### ISSUE THREAD

**Issue by imesh** [wso2/puppet-base#28] opened 2017-07-31 12:24 UTC
The following error was noticed in params.pp file:

==> default: /usr/lib/ruby/vendor_ruby/puppet/application.rb:364:in `run'
==> default: /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:137:in `run'
==> default: /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:91:in `execute'
==> default: /usr/bin/puppet:4:in `<main>'
==> default: Error: "true" is not a boolean.  It looks to be a String at /tmp/vagrant-puppet/modules-e90d403703172cf0704f7817256b65a4/wso2base/manifests/params.pp:43 on node default.private.wso2.com

**Comment by DilanUA** [comment] 2017-11-24 07:16
Closing since this error is not reproducible at the moment.

**Closed as completed by DilanUA** 2017-11-24 07:16 UTC
